name: TEI Publisher CI

on:
  # Run tests for any PRs.
  pull_request:

  workflow_dispatch:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: teipublisher

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker build -t exist-db -f Dockerfile.ci .
      - name: Start docker image
        run: docker run --publish 8080:8080 --name db --detach exist-db
      - name: Run npm install
        run: npm install
      - name: Run tests
        run: npm test
      - name: Stop docker
        run: docker stop db